name: pkgdown

on:
  push:
    branches: [main]

jobs:
  pkgdown:
    runs-on: codeberg-small
    env:
      GITHUB_PAT: ${{ forge.token }}

    steps:
      - uses: https://github.com/actions/checkout@v4

      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: "https://gnoblet.codeberg.page/AddFonts/"
          token: ${{ forge.token }}
          source: docs/
