name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: codeberg-medium
    env:
      GITHUB_PAT: ${{ forge.token }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: https://github.com/actions/checkout@v4

      - uses: https://github.com/r-lib/actions/setup-r@v2
        with:
          r-version: '4.6.0'
          use-public-rspm: 'true'

      - name: Install dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/stable/")
          pak::local_install_dev_deps(ask = FALSE)
          pak::pak("any::rcmdcheck", ask = FALSE)
        shell: Rscript {0}

      - name: Check package
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}
