## Code to prepare `fonts_bunny` dataset
## This script reads the JSON database and converts it to an R data object

library(jsonlite)

# Read the JSON database (generated by Python script)
db_file <- "data-raw/fonts_db_bunny.json"

if (!file.exists(db_file)) {
  stop(
    "Font database not found. Please run: uv run scripts/create_font_db_bunny.py"
  )
}

# Parse the JSON
db <- fromJSON(db_file)

# Extract the fonts data frame
fonts_bunny <- as.data.frame(db$fonts, stringsAsFactors = FALSE)

# Ensure list columns are properly formatted
if ("weights" %in% names(fonts_bunny) && !is.list(fonts_bunny$weights)) {
  fonts_bunny$weights <- I(as.list(fonts_bunny$weights))
}
if ("styles" %in% names(fonts_bunny) && !is.list(fonts_bunny$styles)) {
  fonts_bunny$styles <- I(as.list(fonts_bunny$styles))
}
if ("variants" %in% names(fonts_bunny) && !is.list(fonts_bunny$variants)) {
  fonts_bunny$variants <- I(as.list(fonts_bunny$variants))
}

# Add metadata as attributes
attr(fonts_bunny, "generated") <- db$generated
attr(fonts_bunny, "source") <- db$source
attr(fonts_bunny, "api_endpoint") <- db$api_endpoint
attr(fonts_bunny, "count") <- db$count

# Save to data/
usethis::use_data(fonts_bunny, overwrite = TRUE, internal = TRUE)

# Print summary
# cat("✓ Created fonts_bunny dataset with", nrow(fonts_bunny), "fonts\n")
# cat("✓ Generated:", attr(fonts_bunny, "generated"), "\n")
# cat("✓ Source:", attr(fonts_bunny, "source"), "\n")
# cat("\nFont categories:\n")
# print(table(fonts_bunny$category))
